eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.167:8761/eureka
  instance:
    hostname: localhost
 
microservice:
  gallery-service:
    endpoints:
      endpoint:
        uri: http://gallery-service/gallery/
  image-service:
    endpoints:
      endpoint:
        uri: http://image-service/image/     
